import type { LuaScope, BaseReportArgs } from '../common'

//#region Args

/**
 * Arguments for type analysis.
 */
export type AnalyzeArgs = BaseReportArgs & AnalysisContextArgs

/**
 * Arguments to provide for the shared analysis context.
 */
export interface AnalysisContextArgs {
    /**
     * Flag for whether heuristics should be applied.
     */
    heuristics?: boolean

    /**
     * Flag for whether the analysis is running in the context of a Rosetta initialization or update.
     */
    isForRosetta?: boolean
}

//#endregion

//#region Expressions

/**
 * Information about any Lua literal.
 */
interface LuaLiteral {
    type: 'literal'

    /**
     * A representation of the literal value.
     */
    literal?: string

    /**
     * The type of the literal.
     */
    luaType: LuaType

    /**
     * An identifier for an anonymous function.
     * @see AnalysisContext.getFunctionId
     */
    functionId?: string

    /**
     * An identifier for a table.
     * @see AnalysisContext.getTableId
     */
    tableId?: string

    /**
     * Fields defined in a table constructor.
     */
    fields?: LiteralTableField[]

    /**
     * Flag for whether a function is a method.
     */
    isMethod?: boolean

    /**
     * Parameters for a function literal.
     * These are only populated after analysis finalization.
     */
    parameters?: AnalyzedParameter[]

    /**
     * Return type sets for a function literal.
     * These are only populated after analysis finalization.
     */
    returnTypes?: Set<string>[]
}

/**
 * Information about a Lua variable reference.
 */
interface LuaReference {
    type: 'reference'

    /**
     * The ID of the reference.
     *
     * For globals, this is the identifier name.
     * For locals, this is an internal ID generated by the scope.
     * @see BaseLuaScope.addLocal
     */
    id: string
}

/**
 * Information about a Lua indexing expression (`base[index]`).
 */
interface LuaIndex {
    type: 'index'

    /**
     * The base of the indexing expression.
     */
    base: LuaExpression

    /**
     * The index of the indexing expression.
     */
    index: LuaExpression
}

/**
 * Information about a Lua member expression (`base.member` or `base:member`).
 */
interface LuaMember {
    type: 'member'

    /**
     * The base of the member expression.
     */
    base: LuaExpression

    /**
     * The member being accessed or set in the member expression.
     */
    member: string

    /**
     * The indexer used in the member expression.
     */
    indexer: '.' | ':'
}

/**
 * Information about a call to the `require` function.
 */
interface LuaRequire {
    type: 'require'

    /**
     * The name of the module that was required.
     */
    module: string
}

/**
 * Information about an operation on one or more objects.
 */
interface LuaOperation {
    type: 'operation'

    /**
     * The operator of the operation.
     */
    operator:
        | 'call'
        | '+'
        | '-'
        | '*'
        | '%'
        | '^'
        | '/'
        | '//'
        | '&'
        | '|'
        | '~'
        | '<<'
        | '>>'
        | '..'
        | '~='
        | '=='
        | '<'
        | '<='
        | '>'
        | '>='
        | 'or'
        | 'and'
        | 'not'
        | '-'
        | '~'
        | '#'

    /**
     * The arguments to the operation.
     * For `call` operations, the first argument is the function being called.
     */
    arguments: LuaExpression[]
}

/**
 * Object representing any Lua expression.
 */
export type LuaExpression =
    | LuaLiteral
    | LuaReference
    | LuaIndex
    | LuaMember
    | LuaOperation
    | LuaRequire

/**
 * Basic Lua types, excluding `table` and `function`.
 */
export type BasicLuaType = 'string' | 'number' | 'boolean' | 'nil'

/**
 * Lua data types.
 */
export type LuaType = BasicLuaType | 'table' | 'function'

//#endregion

//#region Tables

/**
 * Represents a string table key (e.g., `{ Key = 0 }`).
 */
interface StringTableKey {
    type: 'string'

    /**
     * The table key identifier.
     */
    name: string
}

/**
 * Represents a literal table key (e.g., `{ [1] = 0 }`).
 */
interface LiteralTableKey {
    type: 'literal'

    /**
     * A representation of the literal value of the key.
     */
    literal: string

    /**
     * The Lua type of a literal table key.
     */
    luaType: BasicLuaType

    /**
     * The field name, for string literal fields.
     */
    name?: string
}

/**
 * Represents the numeric key that Lua would assign for a
 * table field without one (e.g., `{ 1 }`).
 */
interface AutoTableKey {
    type: 'auto'

    /**
     * The numeric key value.
     */
    index: number
}

/**
 * Represents a table key from an arbitrary expression (e.g., `{ [1 + 1] = 2 }`).
 */
interface ExpressionTableKey {
    type: 'expression'

    /**
     * The expression of the key.
     */
    expression: LuaExpression
}

/**
 * Represents a Lua table key.
 */
export type TableKey =
    | StringTableKey
    | AutoTableKey
    | LiteralTableKey
    | ExpressionTableKey

/**
 * Represents a literal table field, including its key and value.
 */
export interface LiteralTableField {
    /**
     * The table key.
     */
    key: TableKey

    /**
     * The table value.
     */
    value: LuaExpression

    /**
     * Types to emit with the table field.
     */
    types?: Set<string>
}

export type LuaTableLiteral = LuaLiteral & { tableId: string }

//#endregion

//#region Analysis Items

/**
 * An analysis item that represents assignment to the result of a `require` call.
 */
export interface RequireAssignmentItem {
    type: 'requireAssignment'

    /**
     * The path for the left-hand side.
     */
    lhs: LuaExpression

    /**
     * An expression representing the require.
     */
    rhs: LuaRequire

    /**
     * The index of the require return value to associate with the item. 1-indexed.
     */
    index?: number
}

/**
 * An analysis item that represents a function definition.
 */
export interface FunctionDefinitionItem {
    type: 'functionDefinition'

    /**
     * The expression for the function name.
     * This is not included for anonymous functions.
     */
    expression?: LuaExpression

    /**
     * The function definition expression.
     */
    literal: LuaExpression

    /**
     * The identifier for the function.
     */
    id: string

    /**
     * `True` if the function is a local function.
     */
    isLocal?: boolean

    /**
     * Parameter names.
     */
    parameters: string[]
}

/**
 * An analysis item that includes information about an assignment to a local or global variable.
 */
export interface AssignmentItem {
    type: 'assignment'

    /**
     * The expression for the left-hand side.
     */
    lhs: LuaExpression

    /**
     * The expression for the right-hand side.
     */
    rhs: LuaExpression

    /**
     * The index to use for a call assignment.
     */
    index?: number
}

/**
 * An analysis item that includes information about the return values of a function.
 * @see AnalysisContext.getFunctionId
 */
export interface ReturnsItem {
    type: 'returns'

    /**
     * The internal function identifier.
     * @see AnalysisContext.getFunctionId
     */
    id: string

    /**
     * Information about the values in the return statement.
     */
    returns: LuaExpression[]
}

/**
 * An analysis item that includes information about the usage of an item.
 */
export interface UsageItem {
    type: 'usage'

    /**
     * The expression for the usage item.
     */
    expression: LuaExpression

    /**
     * Arguments that the usage item was called with.
     * This can be used to narrow the type to `function` and to narrow parameter types.
     */
    arguments?: LuaExpression[]

    /**
     * `True` if the item was used in a numeric for initializer.
     * This can be used to narrow to `number`.
     */
    inNumericFor?: boolean

    /**
     * `True` if the item was found in a concatenation expression.
     * This can be used to narrow to `string | number | table`.
     */
    supportsConcatenation?: boolean

    /**
     * `True` if the item was found as a base in a member or indexer expression.
     * This can be used to narrow to `table | string`.
     */
    supportsIndexing?: boolean

    /**
     * `True` if the item was found as a base in a member or indexer assignment expression.
     * This can be used to narrow to `table`.
     */
    supportsIndexAssignment?: boolean

    /**
     * `True` if the item was found as an operand to the `#` operator.
     * This can be used to narrow to `table | string`.
     */
    supportsLength?: boolean

    /**
     * `True` if the item was found in a mathematical expression.
     * This can be used to narrow to `number | table`.
     */
    supportsMath?: boolean
}

/**
 * An analysis item that includes partial information which should bubble up
 * to the previous scope level.
 */
export interface PartialItem {
    type: 'partial'

    /**
     * A class ID that was referenced.
     * This is used to ensure referenced classes are included.
     */
    seenClassId?: string

    /**
     * Information about a class definition.
     */
    classInfo?: ResolvedClassInfo

    /**
     * Information about a global function.
     */
    functionInfo?: ResolvedFunctionInfo

    /**
     * Information about a call to `require`.
     */
    requireInfo?: ResolvedRequireInfo

    /**
     * Information about a global field.
     */
    fieldInfo?: ResolvedFieldInfo
}

/**
 * Object representing an item for analysis.
 */
export type AnalysisItem =
    | AssignmentItem
    | RequireAssignmentItem
    | FunctionDefinitionItem
    | ReturnsItem
    | UsageItem
    | ResolvedScopeItem
    | PartialItem

//#endregion

//#region Info Objects

/**
 * Information about a Lua expression and the context in which it was used.
 */
export interface LuaExpressionInfo {
    /**
     * The Lua expression.
     */
    expression: LuaExpression

    /**
     * The index of the expression in a call assignment.
     */
    index?: number

    /**
     * Flag for whether the expression is on an instance of a class.
     * Used for field definitions.
     */
    instance?: boolean

    /**
     * Flag for whether the expression was defined within a function scope.
     * Used for field definitions.
     */
    functionLevel?: boolean

    /**
     * Flag for whether the expression was defined within a table constructor literal.
     * Used for field definitions.
     */
    fromLiteral?: boolean

    /**
     * The module which defined the expression.
     * Used for field definitions.
     */
    definingModule?: string
}

/**
 * Information about a Lua function and its types.
 */
export interface FunctionInfo {
    /**
     * The internal function identifier.
     * @see AnalysisContext.getFunctionId
     */
    id: string

    /**
     * The expression used for the function identifier.
     * This is undefined for anonymous functions.
     */
    identifierExpression?: LuaExpression

    /**
     * List of parameter IDs.
     */
    parameters: string[]

    /**
     * List of parameter names.
     */
    parameterNames: string[]

    /**
     * List containing sets of potential parameter types inferred by usage.
     */
    parameterTypes: Set<string>[]

    /**
     * Analyzed return types.
     */
    returnTypes: Set<string>[]

    /**
     * Expressions associated with each return statement.
     */
    returnExpressions: Set<LuaExpression>[]

    /**
     * The minimum number of returns found in the function scope.
     * This is used to make return values nullable.
     */
    minReturns?: number

    /**
     * Flag for whether the function should be treated as a class constructor.
     */
    isConstructor?: boolean
}

/**
 * Information about a Lua table and its fields.
 * Also includes class information.
 */
export interface TableInfo {
    /**
     * The internal table identifier.
     * @see AnalysisContext.getTableId
     */
    id: string

    /**
     * Fields defined in the table constructor.
     */
    literalFields: LiteralTableField[]

    /**
     * Maps Lua literal keys to expressions for their definitions.
     */
    definitions: Map<string, LuaExpressionInfo[]>

    /**
     * The module in which the initial definition of the class was found.
     */
    definingModule?: string

    /**
     * The name of the class assigned to this table.
     */
    className?: string

    /**
     * Flag for whether a class should be local.
     */
    isLocalClass?: boolean

    /**
     * The name used for the original assignment of the table.
     */
    originalName?: string

    /**
     * The ID of the class containing this table as a field.
     */
    containerId?: string

    /**
     * The name for instances of the class assigned to this table.
     */
    instanceName?: string

    /**
     * The table ID for instances of the class assigned to this table.
     */
    instanceId?: string

    /**
     * Whether the table was created from a local `:derive` assignment.
     */
    isLocalDeriveClass?: boolean

    /**
     * The name of the base class, for hidden classes that are ultimately assigned to a global.
     */
    originalBase?: string

    /**
     * The name of the class type, for hidden classes that are ultimately assigned to a global.
     */
    originalDeriveName?: string

    /**
     * Flag for a table belonging to an overwritten class.
     */
    isEmptyClass?: boolean

    /**
     * Flag for a table belonging to a closure-based class.
     */
    isClosureClass?: boolean

    /**
     * Flag for a table belonging to an Atom UI class.
     */
    isAtomUI?: boolean

    /**
     * Flag for a table which is a base Atom UI class.
     */
    isAtomUIBase?: boolean

    /**
     * Flag for emitting the class as a simple table without a class annotation.
     */
    emitAsTable?: boolean
}

/**
 * Information about a Lua table which includes a class.
 */
export type TableInfoWithClass = TableInfo & { className: string }

//#endregion

//#region Resolved

/**
 * Resolved information about a class, before final analysis.
 */
export interface ResolvedClassInfo {
    /**
     * The class name.
     */
    name: string

    /**
     * The internal table identifier.
     * @see AnalysisContext.getTableId
     */
    tableId: string

    /**
     * The module in which the class was initially defined.
     */
    definingModule?: string

    /**
     * The base class that this class extends.
     */
    base?: string

    /**
     * The name to use as the string argument to a `:derive(...)` call
     * in annotations.
     *
     * This is usually the same as `base`, but may differ (typically due to a typo).
     */
    deriveName?: string

    /**
     * Flag for whether the class should be emitted as a local in annotations.
     */
    emitLocal?: boolean
}

/**
 * Resolved information about a global function, before final analysis.
 */
export interface ResolvedFunctionInfo {
    /**
     * The function name.
     */
    name: string

    /**
     * The internal function identifier.
     * @see AnalysisContext.getFunctionId
     */
    functionId: string
}

/**
 * Resolved information about a module-level field (global assignment), before final analysis.
 */
export interface ResolvedFieldInfo {
    /**
     * The name of the field.
     */
    name: string

    /**
     * The set of types for the field.
     */
    types: Set<string>
}

/**
 * Resolved information about a `require` call set to a field, before final analysis.
 */
export interface ResolvedRequireInfo {
    /**
     * The name of the field.
     */
    name: string

    /**
     * The string for the required module.
     */
    module: string
}

/**
 * Resolved information about a return value from a function or module, before final analysis.
 */
export interface ResolvedReturnInfo {
    /**
     * The return types for the return.
     */
    types: Set<string>

    /**
     * The expressions associated with the return index.
     */
    expressions: Set<LuaExpression>
}

/**
 * Resolves information about a scope.
 * This can represent a block scope, function scope, or a module scope.
 */
export interface ResolvedScopeItem {
    type: 'resolved'

    /**
     * The identifier for the scope.
     *
     * For function scopes, this is the internal function identifier.
     * Otherwise, it's the parent scope ID.
     */
    id: string

    /**
     * The classes declared in the scope.
     */
    classes: ResolvedClassInfo[]

    /**
     * The global functions declared in the scope.
     */
    functions: ResolvedFunctionInfo[]

    /**
     * The return values from the scope.
     */
    returns?: ResolvedReturnInfo[]

    /**
     * The require call field assignments in the scope.
     */
    requires: ResolvedRequireInfo[]

    /**
     * The field assignments in the scope.
     */
    fields: ResolvedFieldInfo[]

    /**
     * A set of class names encountered in the scope.
     */
    seenClasses: Set<string>
}

export interface ResolvedModule extends Omit<ResolvedScopeItem, 'returns'> {
    /**
     * The scope for the module.
     */
    scope: LuaScope

    /**
     * The return values from the module.
     */
    returns: ResolvedReturnInfo[]
}

//#endregion

//#region Analyzed

/**
 * A fully analyzed function parameter.
 */
export interface AnalyzedParameter {
    /**
     * The parameter name.
     */
    name: string

    /**
     * Parameter types.
     */
    types: Set<string>
}

/**
 * A fully analyzed global function.
 */
export interface AnalyzedFunction {
    /**
     * The function name.
     */
    name: string

    /**
     * Function parameters.
     */
    parameters: AnalyzedParameter[]

    /**
     * Function return types.
     */
    returnTypes: Set<string>[]

    /**
     * Flag for whether the function is a method.
     */
    isMethod?: boolean

    /**
     * Flag for whether the function is a class constructor.
     */
    isConstructor?: boolean
}

/**
 * A fully analyzed global field assignment.
 */
export interface AnalyzedField {
    /**
     * The global identifier.
     */
    name: string

    /**
     * The types of the field.
     */
    types: Set<string>

    /**
     * The field expression, for rewriting in annotations.
     */
    expression?: LuaExpression
}

/**
 * A fully analyzed table assignment.
 */
export interface AnalyzedTable {
    /**
     * The table identifier.
     */
    name: string

    /**
     * Flag for whether the table should be emitted with a local variable.
     */
    local?: boolean

    /**
     * List of table fields.
     */
    staticFields: AnalyzedField[]

    /**
     * List of table methods. These are annotated using a member expression with `:`.
     */
    methods: AnalyzedFunction[]

    /**
     * List of table functions.
     */
    functions: AnalyzedFunction[]

    /**
     * List of table overloads.
     */
    overloads: AnalyzedFunction[]
}

/**
 * A fully analyzed class.
 */
export interface AnalyzedClass {
    /**
     * The name of the class.
     */
    name: string

    /**
     * The string to use for class base.
     */
    extends?: string

    /**
     * The name to use as the string argument to a `:derive(...)` call.
     */
    deriveName?: string

    /**
     * Flag for whether the class should be emitted with a local variable.
     */
    local?: boolean

    /**
     * Fields to include in the class annotation definition.
     */
    fields: AnalyzedField[]

    /**
     * Fields to include in the class table literal.
     */
    literalFields: LiteralTableField[]

    /**
     * Static fields to include on the class table.
     */
    staticFields: AnalyzedField[]

    /**
     * Additional static fields, for which the field name is an expression indicating
     * a field and subfields.
     *
     * e.g., for a class `X`, one setter field can be `Y.Z` to generate `X.Y.Z = ...`.
     *
     * This exists to handle edge cases for partial classes spread throughout various files (such as `worldgen`).
     */
    setterFields: AnalyzedField[]

    /**
     * Functions to include on the class.
     */
    functions: AnalyzedFunction[]

    /**
     * Methods to include on the class.
     */
    methods: AnalyzedFunction[]

    /**
     * Method constructors to include on the class.
     */
    constructors: AnalyzedFunction[]

    /**
     * Function constructors to include on the class.
     * These are used for closure-based classes.
     */
    functionConstructors: AnalyzedFunction[]

    /**
     * Overloads to include on the class.
     */
    overloads: AnalyzedFunction[]
}

/**
 * A fully analyzed return value.
 */
export interface AnalyzedReturn {
    /**
     * The return expression, for rewriting.
     */
    expression?: LuaExpression

    /**
     * Analyzed return types.
     */
    types: Set<string>
}

/**
 * A fully analyzed module.
 */
export interface AnalyzedModule {
    /**
     * The file identifier for the module.
     */
    id: string

    /**
     * A prefix to include at the start of the annotated module.
     * This exists for the `@meta` annotation.
     */
    prefix?: string

    /**
     * Global module functions.
     */
    functions: AnalyzedFunction[]

    /**
     * Classes declared in the module.
     */
    classes: AnalyzedClass[]

    /**
     * Tables declared in the module.
     */
    tables: AnalyzedTable[]

    /**
     * Global fields declared in the module.
     */
    fields: AnalyzedField[]

    /**
     * Return values of the module.
     */
    returns: AnalyzedReturn[]
}

//#endregion
